name: GitHub Actions Build and Deploy

# 触发条件
on:
  # 手动触发
  workflow_dispatch:
  # push 到指定分支
  push:
    branches:
      - main
    # 只在下列路径变更时触发

  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false


# 设置上海时区
env:
  TZ: Asia/Shanghai



# 任务
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
    steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0 # Not needed if lastUpdated is not enabled
          # - uses: pnpm/action-setup@v3 # Uncomment this if you're using pnpm
          # - uses: oven-sh/setup-bun@v1 # Uncomment this if you're using Bun

      # 安装 pnp
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      # 设置 node 版本
         - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: npm # or pnpm / yarn

      # 设置 ??? 版本
          - name: Setup Pages
            uses: actions/configure-pages@v4
          - name: Install dependencies
            run: npm ci # or pnpm install / yarn install / bun install



      # 打包静态文件
      - name: Build
        env:
          APP_BASE_PATH: /${{ github.repository }}
        run: npm install && npm run build

      # 设置 ??? 版本
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
        path: docs/.vitepress/dist

      # 部署
  deploy:
    environment:
      name: github-pages

    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
